name = "aioptimizer"
compatibility_date = "2024-01-01"

pages_build_output_dir = ".next"

[env.production]
name = "aioptimizer"

# Account ID for Cloudflare
account_id = "d371c76d7e486fbae757ae73a6349bc6"

# Next.js specific configuration
[build]
command = "npm run build"
