[tool.poetry]
name = "aioptimizer"
version = "0.1.0"
description = ""
authors = ["pawel <pawel@werda.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
